export default [
	{
		image: "./imgs/todo1.webp",
		title: "Todo App",
		description: "Frontend mentor challenge made by HTML, CSS and JavaScript",
		preview: "https://mohamedbediwe.github.io/Todo-App/",
		github: "https://github.com/MohamedBediwe/Todo-App",
		techs: "HTML + CSS + JS",
	},
	{
		image: "./imgs/Leon.webp",
		title: "Leon",
		description: "Leon landing page made by HTML and CSS",
		preview: "https://mohamedbediwe.github.io/Leon-Template/",
		github: "https://github.com/MohamedBediwe/Leon-Template",
		techs: "HTML + CSS",
	},
	{
		image: "./imgs/Kasper.webp",
		title: "Kasper",
		description: "Kasper landing page, A HTML and CSS application",
		preview: "https://mohamedbediwe.github.io/Todo-App/",
		github: "https://github.com/MohamedBediwe/Todo-App",
		techs: "HTML + CSS",
	},
	{
		image: "./imgs/Bondi.webp",
		title: "Bondi",
		description: "Boni landing page made by HTML and CSS ",
		preview: "https://mohamedbediwe.github.io/Bondi-template/",
		github: "https://github.com/MohamedBediwe/Bondi-template",
		techs: "HTML + CSS",
	},
	{
		image: "./imgs/Manage.webp",
		title: "Manage",
		description: "Boni landing page made by bootstrap ",
		preview: "https://mohamedbediwe.github.io/Bondi-template/",
		github: "https://github.com/MohamedBediwe/Bondi-template",
		techs: "HTML + CSS",
	},
	{
		image: "./imgs/weather.webp",
		title: "Weather App",
		description:
			"A Weather app that gives the weather conditions for the next weak and the rest of the day hourly ",
		preview: "https://mohamedbediwe.github.io/Weather-App/",
		github: "https://github.com/MohamedBediwe/Weather-App",
		techs: "HTML + CSS + JS",
	},
	{
		image: "./imgs/Elzero.webp",
		title: "Elzero",
		description:
			"Elzero landing page, colorful with animations and elegant styling",
		preview: "https://mohamedbediwe.github.io/Elzero-Web-School-Template/",
		github: "https://github.com/MohamedBediwe/Elzero-Web-School-Template",
		techs: "HTML + CSS + JS",
	},
	{
		image: "./imgs/React-todo.webp",
		title: "Todo App",
		description: "Todo app made by React.js, Write down your todos",
		preview: "https://mohamedbediwe.github.io/React-todo-app/",
		github: "https://github.com/MohamedBediwe/React-todo-app",
		techs: "React.js",
	},
	{
		image: "./imgs/comfy.webp",
		title: "Comfy Sloth Store",
		description:
			"An e-commerce website made by react.js it has authentaction, checkout and more",
		preview: "https://mohamedbediwe.github.io/comfy-sloth-store/",
		github: "https://github.com/MohamedBediwe/comfy-sloth-store",
		techs: "React.js",
	},
	{
		image: "./imgs/Wordle.webp",
		title: "Wordle App",
		description: "A game about guessing a 5 letters word",
		preview: "https://mb-wordle-game.netlify.app/",
		github: "https://github.com/MohamedBediwe/wordle-game",
		techs: "React.js",
	},
	{
		image: "./imgs/Roto-store.webp",
		title: "Roto Store",
		description: "Fullstack project made with PHP, MySQL, React.js and GraphQL",
		preview: "https://mb-wordle-game.netlify.app/",
		github: "https://github.com/MohamedBediwe/wordle-game",
		techs: "PHP + MySQL + React.js + GraphQL",
	},
];
